020

diff --git a/biomni_env/Dockerfile.1 b/biomni_env/Dockerfile.1
--- a/biomni_env/Dockerfile.1
+++ b/biomni_env/Dockerfile.1
@@ -128,6 +128,9 @@ RUN echo $FORCE_R_REBUILD
 RUN echo "options(repos = c(CRAN = 'https://mirrors.ustc.edu.cn/CRAN/'))" > ~/.Rprofile && \
     echo "options(BioC_mirror = 'https://bioconductor.posit.co/')" >> ~/.Rprofile
 
+# 先用conda安装有问题的R包
+RUN /opt/miniconda3/bin/conda install -n biomni_e1 -c conda-forge r-interp --yes || echo "interp package installation failed, continuing..."
+
 COPY --chown=biomni:biomni install_r_packages.R ./
 RUN /opt/miniconda3/envs/biomni_e1/bin/Rscript install_r_packages.R 2>&1 | tee install_r_packages.log || echo "Some R packages may have failed, continuing... (see install_r_packages.log)"
 
